# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SubModuleTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


    # pod 'SubModuleTest', '~> 1.0.3'
    pod 'SubModuleTest/Basic'

    #pod 'SubModuleTest/Core'
    #pod 'SubModuleTest/Hello'
    #pod 'SubModuleTest/GoodBye'

end
