# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SubModuleTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'SubModuleTest'

    # pod 'SubModuleTest/Core'
    # pod 'SubModuleTest/Hello'

end
