# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SubModuleTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'SubModuleTest/Core', :git => 'https://github.com/showthat/SubModuleTest.git', tag: '1.0.10'
  pod 'SubModuleTest/Core', :git => 'https://github.com/showthat/SubModuleTest.git'
  pod 'SubModuleTest/Hello', :git => 'https://github.com/showthat/SubModuleTest.git'
  pod 'SubModuleTest/GoodBye', :git => 'https://github.com/showthat/SubModuleTest.git'
  
  pod 'Alamofire'
  
end
